### ISSUE TITLE
[Q] Where is Micro used?

### ISSUE THREAD

**Issue by spences10** [siddharthkp/github-user#1]
Just curious as to where Micro is used? I see the start script uses it too

https://github.com/siddharthkp/github-user/blob/727dbb811fb89e7973481a49423d39afbf491a99/package.json#L22

**Comment by siddharthkp** [comment]
micro runs the server :)

**Comment by spences10** [comment]
>micro runs the server :)

but, but, where?

Does there not need to be any instantiation of the package other than it being installed? And called via a script?

Sorry, noob :raising_hand_man: here

**Comment by siddharthkp** [comment]
Ah, i get your question now 😄 

micro is a cli tool, so you run it by giving it a file. It will pick up whatever is `exported`

By default, it will pick up `index.js`

**Comment by siddharthkp** [comment]
You can draw a parallel to this with create-react-app which picks up files on it's own 😄

**Comment by spences10** [comment]
Ok, cool, so it's like a dev dependency?

**Comment by siddharthkp** [comment]
Umm, not really.

You still need it to run your app on production.

**Comment by spences10** [comment]
Thanks for explaining Siddharth 👍 

I'll close this now
