### ISSUE TITLE
Educate me pls

### ISSUE THREAD

**Issue by spences10** [siddharthkp/github-user#2]
Hey @siddharthkp 

Sorry to have to log an issue but I'd like to understand what this line of code is doing here, I presume it is parsing the param from the URL?

https://github.com/siddharthkp/github-user/blob/727dbb811fb89e7973481a49423d39afbf491a99/index.js#L9

I don't know what the `.query` part is can you explain?

Also, I think I'd like to understand how you develop an API like this, do you configure via a `.env` with `prod` and `dev` flags?

The reason I'm asking is because I want to make something like Lorem Ipsum where I have an endpoint that I pass `8 words` and it will give a .json response with 8 words. Similarly if I want paragraphs, pass `3 paragraphs` and I'll get a .json response with 3 paragraphs of text.

**Comment by siddharthkp** [comment]
Hi Scott!

Sorry for my garbage code 😅 Let me break this line down so that it's more readable.

Node.js comes with an inbuilt package called [`url`](https://nodejs.org/api/url.html) that has utilities for URL resolution and parsing.

```js
const url = require('url')
```

When you use `url.parse()` on a string, it tries to parse it and return an instance of the [URL Class](https://nodejs.org/api/url.html#url_class_url)

```js
const urlObject = url.parse(req.url)

/*
  url.parse('http://localhost:3000/?username=siddharthkp')

  Url {
    protocol: null,
    slashes: null,
    auth: null,
    host: null,
    port: null,
    hostname: null,
    hash: null,
    search: '?username=siddharthkp',
    query: 'username=siddharthkp',
    pathname: '/',
    path: '/?username=siddharthkp',
    href: '/?username=siddharthkp'
  }
*/
```

An interesting thing about `url.parse()` is that it accepts a [second parameter `parseQueryString`](https://nodejs.org/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost) that helps us parse the `query` part of the Url object. This uses [`querystring.parse`](https://nodejs.org/api/querystring.html) internally.

```js
const urlObject = url.parse(req.url, true)

/*
  url.parse('http://localhost:3000/?username=siddharthkp')

  Url {
    protocol: null,
    slashes: null,
    auth: null,
    host: null,
    port: null,
    hostname: null,
    hash: null,
    search: '?username=siddharthkp',
    query: { username: 'siddharthkp' },
    pathname: '/',
    path: '/?username=siddharthkp',
    href: '/?username=siddharthkp'
  }
*/
```

Notice that the `query` part is now an object!

```js
const urlObject = url.parse(req.url, true)
const query = urlObject.query

// { username: siddharthkp }
```

Now we can take username from this object by referencing the key

```js
const username = query.username
```

or by using ES6 destructuring

```
const { username } = query
```

Putting it all together, this code should be written as:

```js
const url = require('url')

const urlObject = url.parse(req.url, true)
const query = urlObject.query
const { username } = query
```

**Comment by siddharthkp** [comment]
> Also, I think I'd like to understand how you develop an API like this, do you configure via a .env with prod and dev flags?

In this repo, I don't have any environment variables, but when I have to add them. I usually use npmjs.com/dotenv which reads variables from a `.env` file and sets them in `process.env`

Some hosting providers (like now.sh and heroku) let you set `process.env` during deployment, which is a good substitute to `.env` files as you don't want to accidentally commit them in a public repository 😅

**Comment by spences10** [comment]
Thanks @siddharthkp 👍 

This is gold!

>In this repo, I don't have any environment variables, but when I have to add them. I usually use npmjs.com/dotenv which reads variables from a .env file and sets them in process.env

Yes I use `dotenv` in all the Twitter bots I have made it's a great utility, it also lets other people have a better idea of how your app works if you leave something in like a `config.js` that points to the `env` variables.

I think what I was trying to ask, (and articulating myself badly) was how do you test an endpoint in dev vs in prod?

So, let's say in `github-user` when you fire up `npm run start || yarn start` I'm presuming that Micro sets up it's own dev server that you can pass the queries to via `localhost:3000/someQuery` is that how it works? And when you deploy to now it magically (because we all know Zeit products are magic) knows it's in production, right? 

>Some hosting providers (like now.sh and heroku) let you set process.env during deployment, which is a good substitute to .env files as you don't want to accidentally commit them in a public repository 

☝️ been there done that 😄

**Comment by siddharthkp** [comment]
> was how do you test an endpoint in dev vs in prod?
> So, let's say in github-user when you fire up npm run start || yarn start I'm presuming that Micro sets up it's own dev server that you can pass the queries to via localhost:3000/someQuery is that how it works?

Yep, that's right

> And when you deploy to now it magically (because we all know Zeit products are magic) knows it's in production, right?

I'm not sure if it differentiates between environments. now does have some magic to identify the port that micro is running on. Is that what you're talking about here?

**Comment by spences10** [comment]
>I'm not sure if it differentiates between environments. now does have some magic to identify the port that micro is running on. Is that what you're talking about here?

Yeah, it was to identify if I need to do anything like setting dev and prod variables which I have little experience in.
